language: ruby

env:
  global:
  - secure: Qx0zzga92uJ8Mv3yFc1khlRw0O7yCCTKudnuYhoBClIqtsScT2Hrzk+hyTR3JdSIKJsvDS5wIdemG/mpQNVR0g0e9FFQYXf/OWiIzEr5WdhOu01M4C76phDpfXtru1VowIZCWH5ol2qmZgqxW2yML2c3Bw71dNiO+vTIFO7gowBN54Ouu+k/xZ1OrifccAONPbiWh88B91/m0dCMs1QZgheYEc5hcap8ZtjJiUhZRggoK9OPqJukCavBDr50RChW7bVO7Pip8wa0eWSmQw5CQEpcmuoT/9USEmkgMJYmIh2/5PR+aMG+N8naGHcNLqBZKtv92brXKbRoCR+V8NtTbyl9BXw/13i3sm7aS6Keox+PcRA4fIewK+mkRhn4UzXyz0xbbAgP1K7LMGb4rderE6OK03uE3qQFInBYdKd2LnTZ6+ZNMCPeCxWjRbjmXIJU4TQn1Md37zZbyV/N5oekUQOK6XAgUHgWWMC1/+BjFrR+HgX6zgemw7qEh1fl6dHZQ0kAROkyycDzyb9ajdbpjDg85DtAmo6xMIa6H885fkydkqH5w233JedjYIrAF6jhj/aWc2SuCSXeCy36TR/NIkI2NeXnDfDcq5pXHE0X5VD1BWT1W7vvg13SanSUmyO4d+mPpkaijni9AFXwkjKU/v0IpkRry2rmFnmb1ybEcj8=
  - secure: 14D3ZusDuQC9T1sV2AZQBkJpo7I3WcCwLJujFYXi/WVUoaM5qtGgx5u2FPMLT2mErt4laE5yCSz4vxc1qQkbtmuZkg7FcVj+bfeBT2Q7a6ox886k2FCuYLxvpSTwjFaWmyYyL10RJcYh6BRqjWJN17fSCPRpj0sbysAurUzGYtz+Y/bxVGwepr4MliEVL7CnH9/qstH0NxwdEyJEJOgDe/ft/9vA6IIfB10SV3QNQ0vkBXVjP2ll+XW/+17ChJkgV1aFldimrOPsFBIDZeEVh+FLDYePp9b6j+J+E2SNVTELHNcGpZ0R2Vmdg48juR3Zfupj1fiZRd8Xu7jaCc5NeUhVR5UPKchb/NPNGol6hsCVNlfZ1EyDE+SnE/THeFquHeBQe8WHy+CdhXw1U4jAkeddKNLl5lBL6SrWl8EGE6La9+j+c4zeQ170LckITRKTUJrwYocN7s+FFQ4PCrWhjRuLFGyeh1PWnpk7PgvH6LMboL0faCQf0nW88H8wHn/PuNblWWXYR32SjxIF14PhaYdI/a/yU4ehGjdRdR2VsTgF6of47XZ/zjtc/Q6seZjBV3GjRHl7Ddt0f4i0ZeBBDKifEM8KvId+C8udvfd/oddyuz7oCv5bC0v2bt+fiR5g9Tg+Nrv87nJdOJfN00yWIrAoNGEEK5ZJ66WyMw5Ymao=
  - COMMIT=${TRAVIS_COMMIT::8}

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - huebrops:oQZYgN0fvoyFBVjuIUQREc8h
    - huebrops:oQZYgN0fvoyFBVjuIUQREc8h#ci

rvm:
- 2.5.0

services:
- docker

bundler_args: "--jobs=2"

before_install:
- gem update --system
- gem --version

script:
- bundle exec rspec

cache: bundler

after_success:
- export REPO=gabriel2012rissi/my-webserver
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
